/**
 * Destination & Activity Knowledge Service
 * Provides rich, verified destination metadata, coordinates, signature sights, and activity catalogs.
 */

export const DESTINATION_DATABASE = [
  {
    id: 'dest-japan-golden-route',
    name: 'Japan (Tokyo, Kyoto, Osaka)',
    aliases: ['japan', 'golden route', 'tokyo kyoto osaka', 'nippon', 'nihon'],
    country: 'Japan',
    region: 'Honshu',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600&h=900&fit=crop',
    tagline: 'Ancient shrines, neon metropolises, high-speed rail, and gastronomic wonder',
    idealDays: 7,
    avgDailyCostJPY: 35000,
    bestSeasons: ['Spring (Sakura)', 'Autumn (Momiji)', 'Winter', 'Early Summer'],
    cities: ['Tokyo', 'Kyoto', 'Osaka', 'Nara', 'Hakone'],
  },
  {
    id: 'dest-tokyo',
    name: 'Tokyo',
    aliases: ['tokyo', 'edo', 'shibuya', 'shinjuku'],
    country: 'Japan',
    region: 'Kanto',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1600&h=900&fit=crop',
    tagline: 'The world’s most dynamic futuristic metropolis and culinary capital',
    idealDays: 4,
    avgDailyCostJPY: 32000,
    bestSeasons: ['All Year', 'Spring', 'Autumn'],
    cities: ['Tokyo'],
  },
  {
    id: 'dest-kyoto',
    name: 'Kyoto',
    aliases: ['kyoto', 'gion', 'arashiyama', 'fushimi'],
    country: 'Japan',
    region: 'Kansai',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600&h=900&fit=crop',
    tagline: 'The imperial cultural heart of Japan with over 2,000 temples and tranquil gardens',
    idealDays: 3,
    avgDailyCostJPY: 38000,
    bestSeasons: ['Spring', 'Autumn'],
    cities: ['Kyoto'],
  },
  {
    id: 'dest-osaka',
    name: 'Osaka',
    aliases: ['osaka', 'dotonbori', 'namba', 'umeda'],
    country: 'Japan',
    region: 'Kansai',
    coordinates: { lat: 34.6937, lng: 135.5023 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1590559899731-a382571f28d9?w=1600&h=900&fit=crop',
    tagline: 'The nation’s kitchen: vibrant street food, comedy culture, and neon canals',
    idealDays: 2,
    avgDailyCostJPY: 28000,
    bestSeasons: ['Spring', 'Autumn', 'Winter'],
    cities: ['Osaka'],
  },
  {
    id: 'dest-hokkaido',
    name: 'Hokkaido (Sapporo, Otaru, Niseko)',
    aliases: ['hokkaido', 'sapporo', 'niseko', 'furano'],
    country: 'Japan',
    region: 'Hokkaido',
    coordinates: { lat: 43.0618, lng: 141.3545 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1610375228550-d5cabc1e3950?w=1600&h=900&fit=crop',
    tagline: 'Pristine powder snow, volcanic onsen spas, lavender valleys, and fresh king crab',
    idealDays: 5,
    avgDailyCostJPY: 42000,
    bestSeasons: ['Winter (Snow)', 'Summer (Lavender)'],
    cities: ['Sapporo', 'Otaru', 'Hakodate', 'Niseko'],
  },
  {
    id: 'dest-hakone',
    name: 'Hakone & Mount Fuji',
    aliases: ['hakone', 'mt fuji', 'mount fuji', 'fuji five lakes', 'lake ashi'],
    country: 'Japan',
    region: 'Chubu',
    coordinates: { lat: 35.2324, lng: 139.1069 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1600&h=900&fit=crop',
    tagline: 'Hot spring mountain retreats with open-air baths gazing at Mount Fuji',
    idealDays: 2,
    avgDailyCostJPY: 48000,
    bestSeasons: ['Autumn', 'Spring', 'Winter'],
    cities: ['Hakone', 'Fujikawaguchiko'],
  },
  {
    id: 'dest-hiroshima',
    name: 'Hiroshima & Miyajima Island',
    aliases: ['hiroshima', 'miyajima', 'itsukushima'],
    country: 'Japan',
    region: 'Chugoku',
    coordinates: { lat: 34.3853, lng: 132.4553 },
    timezone: 'Asia/Tokyo',
    currency: 'JPY',
    heroImage: 'https://images.unsplash.com/photo-1576675466969-38eeae4b41f6?w=1600&h=900&fit=crop',
    tagline: 'Floating vermilion Torii gate, Peace Memorial Park, and savory Hiroshima-style okonomiyaki',
    idealDays: 2,
    avgDailyCostJPY: 29000,
    bestSeasons: ['Spring', 'Autumn'],
    cities: ['Hiroshima', 'Miyajima'],
  },
  {
    id: 'dest-paris',
    name: 'Paris, France',
    aliases: ['paris', 'france'],
    country: 'France',
    region: 'Île-de-France',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    timezone: 'Europe/Paris',
    currency: 'EUR',
    heroImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&h=900&fit=crop',
    tagline: 'The City of Light: art museums, haute cuisine, Haussmann architecture, and romantic avenues',
    idealDays: 5,
    avgDailyCostJPY: 45000,
    bestSeasons: ['Spring', 'Autumn'],
    cities: ['Paris'],
  },
  {
    id: 'dest-rome',
    name: 'Rome, Italy',
    aliases: ['rome', 'italy', 'roma'],
    country: 'Italy',
    region: 'Lazio',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    timezone: 'Europe/Rome',
    currency: 'EUR',
    heroImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1600&h=900&fit=crop',
    tagline: 'The Eternal City: ancient Colosseum, Vatican treasures, espresso culture, and trattorias',
    idealDays: 4,
    avgDailyCostJPY: 38000,
    bestSeasons: ['Spring', 'Autumn'],
    cities: ['Rome'],
  },
  {
    id: 'dest-bali',
    name: 'Bali, Indonesia',
    aliases: ['bali', 'indonesia', 'ubud', 'seminyak'],
    country: 'Indonesia',
    region: 'Bali',
    coordinates: { lat: -8.4095, lng: 115.1889 },
    timezone: 'Asia/Makassar',
    currency: 'USD',
    heroImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1600&h=900&fit=crop',
    tagline: 'Island of the Gods: emerald rice terraces, cliffside temples, yoga sanctuaries, and surf beaches',
    idealDays: 6,
    avgDailyCostJPY: 22000,
    bestSeasons: ['Dry Season (April - October)'],
    cities: ['Ubud', 'Canggu', 'Seminyak', 'Uluwatu'],
  },
];

/**
 * Searches the destination catalog by name or alias keyword.
 */
export function findDestination(query) {
  if (!query || typeof query !== 'string') return DESTINATION_DATABASE[0];
  const q = query.toLowerCase().trim();

  // Exact or alias match
  const found = DESTINATION_DATABASE.find(d => 
    d.name.toLowerCase().includes(q) || 
    d.aliases.some(alias => q.includes(alias) || alias.includes(q))
  );

  return found || DESTINATION_DATABASE[0];
}

/**
 * Generates tailored activities catalog based on destination and themes.
 */
export function getCuratedActivities(_destinationName, _interests = []) {
  const catalog = [
    {
      title: 'Sunrise Walk at Fushimi Inari Taisha',
      type: 'activity',
      location: { name: 'Fushimi Inari Taisha', address: 'Fushimi Ward, Kyoto', lat: 34.9671, lng: 135.7727 },
      durationMinutes: 120,
      cost: 0,
      tags: ['Culture', 'Temples', 'Photography'],
      rating: 5.0,
      description: 'Hike through 10,000 vermilion torii gates winding up the sacred mountain before crowds awake.',
    },
    {
      title: 'teamLab Planets Immersive Digital Art',
      type: 'activity',
      location: { name: 'teamLab Planets', address: 'Toyosu, Tokyo', lat: 35.6518, lng: 139.7925 },
      durationMinutes: 150,
      cost: 3800,
      tags: ['Modern Art', 'Interactive', 'Must-See'],
      rating: 4.9,
      description: 'Wade through barefoot water installations and crystalline mirror infinities.',
    },
    {
      title: 'Shibuya Sky Observation Deck at Sunset',
      type: 'activity',
      location: { name: 'Shibuya Scramble Square', address: 'Shibuya, Tokyo', lat: 35.6585, lng: 139.7022 },
      durationMinutes: 90,
      cost: 2500,
      tags: ['Views', 'Iconic', 'Sunset'],
      rating: 4.9,
      description: 'Open-air rooftop observatory with glass corners overlooking the world’s busiest pedestrian crossing.',
    },
    {
      title: 'Arashiyama Bamboo Forest & Sagano Romantic Train',
      type: 'activity',
      location: { name: 'Arashiyama', address: 'Ukyo Ward, Kyoto', lat: 35.0169, lng: 135.6713 },
      durationMinutes: 180,
      cost: 1400,
      tags: ['Nature', 'Scenic', 'Gardens'],
      rating: 4.8,
      description: 'Walk among towering green bamboo followed by an open-air scenic locomotive ride along the Hozu River.',
    },
    {
      title: 'Dotonbori Street Food & Night Market Tour',
      type: 'meal',
      location: { name: 'Dotonbori', address: 'Chuo Ward, Osaka', lat: 34.6687, lng: 135.5013 },
      durationMinutes: 120,
      cost: 3500,
      tags: ['Culinary', 'Street Food', 'Nightlife'],
      rating: 4.8,
      description: 'Sample piping hot takoyaki, grilled kobe beef skewers, and gyoza under neon billboards.',
    },
    {
      title: 'Private Machiya Zen Tea Whisking Ceremony',
      type: 'activity',
      location: { name: 'Camellia Garden', address: 'Higashiyama, Kyoto', lat: 34.9995, lng: 135.7801 },
      durationMinutes: 90,
      cost: 5500,
      tags: ['Traditional', 'Tea', 'Zen'],
      rating: 4.9,
      description: 'Master the meditative steps of whisking ceremonial Uji matcha in a 100-year-old wooden teahouse.',
    },
    {
      title: 'Tsukiji Outer Fish Market Breakfast Tasting',
      type: 'meal',
      location: { name: 'Tsukiji Outer Market', address: 'Chuo City, Tokyo', lat: 35.6655, lng: 139.7708 },
      durationMinutes: 90,
      cost: 3200,
      tags: ['Culinary', 'Seafood', 'Breakfast'],
      rating: 4.7,
      description: 'Taste tamagoyaki rolled omelettes, uni sea urchin buns, and fresh tuna sashimi bowls.',
    },
    {
      title: 'Osaka Castle Citadel & Stone Rampart Gardens',
      type: 'activity',
      location: { name: 'Osaka Castle', address: 'Chuo Ward, Osaka', lat: 34.6873, lng: 135.5262 },
      durationMinutes: 120,
      cost: 600,
      tags: ['History', 'Castle', 'Architecture'],
      rating: 4.7,
      description: 'Tour the eight-story museum tower, gilded dragon roof tiles, and 60-meter high stone defensive walls.',
    },
    {
      title: 'Akihabara Electronics & Retro Gaming Safari',
      type: 'activity',
      location: { name: 'Akihabara Electric Town', address: 'Chiyoda, Tokyo', lat: 35.6983, lng: 139.7731 },
      durationMinutes: 120,
      cost: 1500,
      tags: ['Pop Culture', 'Gaming', 'Anime'],
      rating: 4.6,
      description: 'Explore multi-story retro arcade towers (Super Potato) and vintage electronics alleys.',
    },
    {
      title: 'Kiyomizu-dera Cliffside Wooden Temple Terrace',
      type: 'activity',
      location: { name: 'Kiyomizu-dera', address: 'Higashiyama, Kyoto', lat: 34.9949, lng: 135.7850 },
      durationMinutes: 120,
      cost: 500,
      tags: ['UNESCO', 'Temples', 'Views'],
      rating: 4.9,
      description: 'Marvel at the ancient mortise-and-tenon wooden terrace built without a single nail overlooking the valley.',
    },
  ];

  return catalog;
}
