/**
 * Persistence & Storage Service
 * Handles localStorage synchronization, JSON import/export, and Markdown itinerary generation.
 */

const STORAGE_KEY = 'nihon_ai_travel_plan_v1';
const HISTORY_KEY = 'nihon_ai_travel_history_v1';
const SETTINGS_KEY = 'nihon_ai_planner_settings_v1';

export function saveStateToStorage(state) {
  try {
    if (!state) return;
    const serialized = JSON.stringify(state);
    localStorage.setItem(STORAGE_KEY, serialized);
  } catch (err) {
    console.error('Failed to persist travel plan state to localStorage:', err);
  }
}

export function loadStateFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (parsed && parsed.trip && parsed.itinerary && Array.isArray(parsed.itinerary.days)) {
      return parsed;
    }
    return null;
  } catch (err) {
    console.warn('Failed to parse saved state from storage, resetting:', err);
    return null;
  }
}

export function clearSavedState() {
  try {
    localStorage.removeItem(STORAGE_KEY);
    localStorage.removeItem(HISTORY_KEY);
  } catch (err) {
    console.error('Failed to clear storage:', err);
  }
}

export function saveSettings(settings) {
  try {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
  } catch (err) {
    console.error('Failed to save settings:', err);
  }
}

export function loadSettings() {
  try {
    const raw = localStorage.getItem(SETTINGS_KEY);
    return raw ? JSON.parse(raw) : { llmProvider: 'local', apiKey: '', model: 'gemini-1.5-flash', preferredCurrency: 'JPY' };
  } catch {
    return { llmProvider: 'local', apiKey: '', model: 'gemini-1.5-flash', preferredCurrency: 'JPY' };
  }
}

/**
 * Generates an elegant Markdown itinerary document ready for export or printing.
 */
export function generateMarkdownItinerary(state) {
  const { trip, itinerary, lodging, transit } = state;
  const days = itinerary?.days || [];

  let md = `# 🗾 ${trip.title}\n\n`;
  md += `**Destination:** ${trip.destination.name} (${trip.destination.country})\n`;
  md += `**Dates:** ${trip.dates.startDate} to ${trip.dates.endDate} (${trip.dates.durationDays} Days)\n`;
  md += `**Travelers:** ${trip.travelers.count} (${trip.travelers.type})\n`;
  md += `**Budget:** ${trip.budget.currency} ${trip.budget.total.toLocaleString()} (Estimated: ${trip.budget.currency} ${trip.budget.spent.toLocaleString()})\n`;
  md += `**Pace:** ${trip.preferences.pace.toUpperCase()} | **Interests:** ${trip.preferences.interests.join(', ')}\n\n`;
  md += `---\n\n`;

  md += `## 📅 Day-by-Day Schedule\n\n`;
  days.forEach(day => {
    md += `### Day ${day.dayNumber}: ${day.title} (${day.date})\n`;
    md += `*Location: ${day.location} | Weather: ${day.weather?.tempC || 20}°C, ${day.weather?.condition || 'Clear'}*\n\n`;

    if (day.items && day.items.length > 0) {
      day.items.forEach(item => {
        const time = item.startTime ? `\`${item.startTime} - ${item.endTime}\`` : '';
        const cost = item.cost > 0 ? `| Cost: ¥${item.cost.toLocaleString()}` : '| Free';
        md += `- ${time} **${item.title}** (${item.type.toUpperCase()}) ${cost}\n`;
        if (item.description) md += `  ${item.description}\n`;
        if (item.location?.name) md += `  📍 *${item.location.name}*\n`;
      });
    } else {
      md += `*No activities scheduled yet for this day.*\n`;
    }
    md += `\n`;
  });

  if (lodging && lodging.length > 0) {
    md += `## 🏨 Accommodations\n\n`;
    lodging.filter(l => l.isSelected).forEach(l => {
      md += `* **${l.name}** (${l.city}, ${l.neighborhood})\n`;
      md += `  - Type: ${l.type} | Rating: ⭐ ${l.rating}\n`;
      md += `  - Rate: ¥${l.pricePerNight.toLocaleString()} / night (${l.nights || 2} nights)\n`;
      md += `  - Location: ${l.proximity}\n\n`;
    });
  }

  if (transit && transit.length > 0) {
    md += `## 🚅 Transit & Intercity Rail\n\n`;
    transit.forEach(t => {
      md += `* **${t.name}** (${t.mode})\n`;
      md += `  - Route: ${t.from} ➔ ${t.to}\n`;
      md += `  - Time: ${t.departureTime || 'TBD'} (${t.duration}) | Class: ${t.seatClass}\n`;
      md += `  - Fare: ¥${t.cost.toLocaleString()} (Ref: ${t.bookingReference || 'N/A'})\n\n`;
    });
  }

  md += `---\n*Generated by AI Travel Planner • ${new Date().toLocaleDateString()}*\n`;
  return md;
}

/**
 * Downloads a text or JSON file in the browser.
 */
export function downloadFile(content, filename, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
