/**
 * NLP & Intent Intermediate Representation Types
 */

export const INTENT_ACTIONS = {
  PLAN_TRIP: 'PLAN_TRIP',
  MODIFY_DATES: 'MODIFY_DATES',
  ADD_ACTIVITY: 'ADD_ACTIVITY',
  REMOVE_ACTIVITY: 'REMOVE_ACTIVITY',
  UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',
  REORDER_DAYS: 'REORDER_DAYS',
  SEARCH_LODGING: 'SEARCH_LODGING',
  SELECT_LODGING: 'SELECT_LODGING',
  SEARCH_TRANSIT: 'SEARCH_TRANSIT',
  OPTIMIZE_ROUTE: 'OPTIMIZE_ROUTE',
  CALCULATE_BUDGET: 'CALCULATE_BUDGET',
  FILTER_INTERESTS: 'FILTER_INTERESTS',
  ASK_RECOMMENDATION: 'ASK_RECOMMENDATION',
  CLARIFY_ANSWER: 'CLARIFY_ANSWER',
  UNDO: 'UNDO',
  REDO: 'REDO',
  RESET: 'RESET',
  UNKNOWN: 'UNKNOWN',
};

export const CLARIFICATION_PRIORITY = {
  BLOCKING: 'blocking', // Cannot execute core action without this
  RECOMMENDED: 'recommended', // Reasonable default available, but good to clarify
  OPTIONAL: 'optional', // Fine-tuning
};
