/**
 * Canonical Application State Definitions & Defaults
 * Decoupled from UI, serializable, versionable, persistable, and extensible.
 */

export const BUDGET_TIERS = {
  BUDGET: 'budget',
  MODERATE: 'moderate',
  LUXURY: 'luxury',
  ULTRA_LUXURY: 'ultra-luxury',
};

export const TRAVEL_STYLES = {
  SOLO: 'solo',
  COUPLE: 'couple',
  FAMILY: 'family',
  FRIENDS: 'friends',
  GROUP: 'group',
};

export const TRIP_PACES = {
  RELAXED: 'relaxed',
  MODERATE: 'moderate',
  PACKED: 'packed',
};

export const ITEM_TYPES = {
  ACTIVITY: 'activity',
  TRANSPORT: 'transport',
  LODGING: 'lodging',
  MEAL: 'meal',
  LEISURE: 'leisure',
};

export const BOOKING_STATUS = {
  UNBOOKED: 'unbooked',
  RECOMMENDED: 'recommended',
  CONFIRMED: 'confirmed',
};

/**
 * Creates a fresh, canonical initial trip state.
 */
export function createInitialTripState() {
  return {
    trip: {
      id: 'trip-japan-2026-default',
      title: 'Golden Route: Tokyo, Kyoto & Osaka Journey',
      status: 'planning', // 'planning' | 'confirmed' | 'archived'
      destination: {
        name: 'Japan (Tokyo, Kyoto, Osaka)',
        country: 'Japan',
        region: 'Honshu',
        coordinates: { lat: 35.6762, lng: 139.6503 },
        timezone: 'Asia/Tokyo',
        currency: 'JPY',
        heroImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600&h=900&fit=crop',
      },
      dates: {
        startDate: '2026-10-10',
        endDate: '2026-10-16',
        durationDays: 7,
        isFlexible: true,
        season: 'autumn',
      },
      travelers: {
        count: 2,
        adults: 2,
        children: 0,
        type: TRAVEL_STYLES.COUPLE,
      },
      budget: {
        total: 450000, // in selected currency (JPY default)
        spent: 312000,
        currency: 'JPY',
        tier: BUDGET_TIERS.MODERATE,
        breakdown: {
          transport: 68000,
          lodging: 154000,
          activities: 48000,
          dining: 42000,
          buffer: 138000,
        },
      },
      preferences: {
        pace: TRIP_PACES.MODERATE,
        interests: ['Culture & Temples', 'Culinary & Street Food', 'Gardens', 'Modern Architecture', 'High-Speed Rail'],
        dietary: ['No Restrictions'],
        accommodationTypes: ['Ryokan', 'Boutique Hotel'],
        transitPreferences: ['Shinkansen Bullet Train', 'Subway / Metro'],
      },
      constraints: {
        mustSee: ['Fushimi Inari Taisha', 'Shibuya Sky', 'Dotonbori'],
        avoid: ['Excessive Crowds during peak noon'],
        maxTransitHoursPerDay: 3.5,
      },
    },

    itinerary: {
      days: [
        {
          dayNumber: 1,
          date: '2026-10-10',
          title: 'Arrival in Tokyo & Shibuya Crossing',
          location: 'Tokyo',
          weather: { tempC: 21, condition: 'Sunny', icon: 'Sun' },
          items: [
            {
              id: 'item-1-1',
              type: ITEM_TYPES.TRANSPORT,
              title: 'Arrival at Narita / Haneda & Narita Express to Shibuya',
              description: 'Clear customs, pick up Pocket Wi-Fi & IC Card, take high-speed express train to central Tokyo.',
              startTime: '14:00',
              endTime: '15:30',
              durationMinutes: 90,
              cost: 3200,
              location: { name: 'Shibuya Station', address: 'Shibuya, Tokyo', lat: 35.6580, lng: 139.7016 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Transit', 'Airport Transfer'],
              rating: 4.8,
            },
            {
              id: 'item-1-2',
              type: ITEM_TYPES.LODGING,
              title: 'Check-in: Cerulean Tower Tokyu Hotel',
              description: 'Drop luggage and freshen up in panoramic city view suite overlooking the metropolis.',
              startTime: '16:00',
              endTime: '17:00',
              durationMinutes: 60,
              cost: 26000,
              location: { name: 'Cerulean Tower Tokyu Hotel', address: '26-1 Sakuragaokacho, Shibuya City', lat: 35.6560, lng: 139.6997 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Lodging', 'Check-in'],
              rating: 4.7,
            },
            {
              id: 'item-1-3',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Shibuya Sky Observation Deck at Sunset',
              description: 'Experience 360-degree open-air rooftop views over Shibuya Crossing and Mount Fuji silhouette.',
              startTime: '17:30',
              endTime: '19:00',
              durationMinutes: 90,
              cost: 2500,
              location: { name: 'Shibuya Sky', address: '2 Chome-24-12 Shibuya, Tokyo', lat: 35.6585, lng: 139.7022 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Views', 'Iconic', 'Sunset'],
              rating: 4.9,
            },
            {
              id: 'item-1-4',
              type: ITEM_TYPES.MEAL,
              title: 'Dinner: Nonbei Yokocho Yakitori Alley',
              description: 'Intimate atmospheric izakaya experience tasting charcoal-grilled yakitori skewers and draft craft beer.',
              startTime: '19:30',
              endTime: '21:00',
              durationMinutes: 90,
              cost: 4500,
              location: { name: 'Nonbei Yokocho', address: '1 Chome-25-10 Shibuya, Tokyo', lat: 35.6601, lng: 139.7018 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Culinary', 'Izakaya', 'Nightlife'],
              rating: 4.6,
            },
          ],
        },
        {
          dayNumber: 2,
          date: '2026-10-11',
          title: 'Tradition Meets Tomorrow: Asakusa & teamLab Planets',
          location: 'Tokyo',
          weather: { tempC: 22, condition: 'Partly Cloudy', icon: 'CloudSun' },
          items: [
            {
              id: 'item-2-1',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Sensō-ji Temple & Nakamise Dori Morning Walk',
              description: 'Tokyo’s oldest Buddhist temple. Walk through the Kaminarimon gate before mid-day crowds gather.',
              startTime: '08:30',
              endTime: '10:30',
              durationMinutes: 120,
              cost: 0,
              location: { name: 'Sensō-ji', address: '2 Chome-3-1 Asakusa, Taito City, Tokyo', lat: 35.7148, lng: 139.7967 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Culture', 'Temple', 'Heritage'],
              rating: 4.8,
            },
            {
              id: 'item-2-2',
              type: ITEM_TYPES.MEAL,
              title: 'Lunch: Traditional Asakusa Soba or Tempura Daikokuya',
              description: 'Authentic Tokyo-style sesame tempura bowl with dipping dashi broth.',
              startTime: '11:30',
              endTime: '12:30',
              durationMinutes: 60,
              cost: 2200,
              location: { name: 'Daikokuya Tempura', address: '1 Chome-38-10 Asakusa, Taito City', lat: 35.7130, lng: 139.7942 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Culinary', 'Lunch'],
              rating: 4.5,
            },
            {
              id: 'item-2-3',
              type: ITEM_TYPES.ACTIVITY,
              title: 'teamLab Planets Immersive Digital Art',
              description: 'Walk through water, floating flower gardens, and kaleidoscopic crystal light universes.',
              startTime: '14:30',
              endTime: '17:00',
              durationMinutes: 150,
              cost: 3800,
              location: { name: 'teamLab Planets TOKYO', address: '6 Chome-1-16 Toyosu, Koto City', lat: 35.6518, lng: 139.7925 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Digital Art', 'Interactive', 'Modern'],
              rating: 4.9,
            },
            {
              id: 'item-2-4',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Ginza Evening Architecture Stroll & Cocktails',
              description: 'Walk through luxury boutiques, kabuki theatre exterior, and enjoy a cocktail at Bar High Five.',
              startTime: '18:30',
              endTime: '21:00',
              durationMinutes: 150,
              cost: 6000,
              location: { name: 'Ginza Six', address: '6 Chome-10-1 Ginza, Chuo City, Tokyo', lat: 35.6696, lng: 139.7640 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Architecture', 'Nightlife'],
              rating: 4.7,
            },
          ],
        },
        {
          dayNumber: 3,
          date: '2026-10-12',
          title: 'Shinkansen Bullet Train to Ancient Kyoto',
          location: 'Kyoto',
          weather: { tempC: 20, condition: 'Sunny', icon: 'Sun' },
          items: [
            {
              id: 'item-3-1',
              type: ITEM_TYPES.TRANSPORT,
              title: 'Tokaido Shinkansen Nozomi (Tokyo Station -> Kyoto Station)',
              description: 'Ride the world-renowned 300 km/h bullet train past Mount Fuji in comfortable reserved Green Car seating.',
              startTime: '09:00',
              endTime: '11:15',
              durationMinutes: 135,
              cost: 14200,
              location: { name: 'Kyoto Station', address: 'Higashishiokojicho, Shimogyo Ward, Kyoto', lat: 34.9858, lng: 135.7588 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['High-Speed Rail', 'Shinkansen', 'Scenic'],
              rating: 4.9,
            },
            {
              id: 'item-3-2',
              type: ITEM_TYPES.LODGING,
              title: 'Check-in: The Thousand Kyoto / Traditional Ryokan',
              description: 'Check into refined minimalist luxury sanctuary steps from the tranquil Higashiyama hills.',
              startTime: '12:00',
              endTime: '13:00',
              durationMinutes: 60,
              cost: 32000,
              location: { name: 'The Thousand Kyoto', address: '570 Higashishiokojicho, Shimogyo Ward', lat: 34.9870, lng: 135.7605 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Lodging', 'Ryokan'],
              rating: 4.9,
            },
            {
              id: 'item-3-3',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Kiyomizu-dera Wooden Stage & Ninenzaka Historic Slopes',
              description: 'Perched cliffside temple offering commanding Kyoto valley panoramas framed by vibrant autumn maple foliage.',
              startTime: '14:30',
              endTime: '17:00',
              durationMinutes: 150,
              cost: 500,
              location: { name: 'Kiyomizu-dera', address: '1 Chome-294 Kiyomizu, Higashiyama Ward', lat: 34.9949, lng: 135.7850 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['UNESCO World Heritage', 'Temples', 'Photography'],
              rating: 4.9,
            },
            {
              id: 'item-3-4',
              type: ITEM_TYPES.MEAL,
              title: 'Traditional Kyoto Kaiseki Multi-Course Dinner in Gion',
              description: 'Seasonal multi-course banquet showcasing local Kamo eggplant, yuba tofu, and wagyu beef.',
              startTime: '18:30',
              endTime: '20:30',
              durationMinutes: 120,
              cost: 12000,
              location: { name: 'Gion Nanba', address: 'Gionmachi Kitagawa, Higashiyama Ward, Kyoto', lat: 35.0037, lng: 135.7750 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Kaiseki', 'Fine Dining', 'Michelin Star'],
              rating: 4.9,
            },
          ],
        },
        {
          dayNumber: 4,
          date: '2026-10-13',
          title: 'Torii Gates of Fushimi Inari & Arashiyama Bamboo',
          location: 'Kyoto',
          weather: { tempC: 19, condition: 'Partly Cloudy', icon: 'CloudSun' },
          items: [
            {
              id: 'item-4-1',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Early Morning Hike: Fushimi Inari 10,000 Vermilion Torii Path',
              description: 'Ascend Mount Inari winding through the endless iconic red torii gates as morning mist filters through the cedars.',
              startTime: '07:30',
              endTime: '09:45',
              durationMinutes: 135,
              cost: 0,
              location: { name: 'Fushimi Inari Taisha', address: '68 Fukakusa Yabunouchicho, Fushimi Ward', lat: 34.9671, lng: 135.7727 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Spiritual', 'Must-See', 'Hike'],
              rating: 5.0,
            },
            {
              id: 'item-4-2',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Arashiyama Sagano Bamboo Grove & Tenryu-ji Zen Garden',
              description: 'Towering green bamboo stalks swaying with the wind, followed by a stroll in Tenryu-ji Sogenchi landscape pond.',
              startTime: '11:00',
              endTime: '13:30',
              durationMinutes: 150,
              cost: 600,
              location: { name: 'Arashiyama Bamboo Grove', address: 'Sagatenryuji Susukinobabacho, Ukyo Ward', lat: 35.0169, lng: 135.6713 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Nature', 'Zen Garden', 'Photography'],
              rating: 4.8,
            },
            {
              id: 'item-4-3',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Private Matcha Whisking & Zen Tea Ceremony in Camellia Garden',
              description: 'Learn the sacred philosophy of wabi-sabi and Ichigo Ichie in a 100-year-old preserved Machiya teahouse.',
              startTime: '15:00',
              endTime: '16:30',
              durationMinutes: 90,
              cost: 5500,
              location: { name: 'Camellia Tea Ceremony', address: '349 Masuyacho, Higashiyama Ward, Kyoto', lat: 34.9995, lng: 135.7801 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Culture', 'Tea Ceremony', 'Traditional'],
              rating: 4.9,
            },
            {
              id: 'item-4-4',
              type: ITEM_TYPES.MEAL,
              title: 'Pontocho Alley Riverside Dining (Kawayuka Terrace)',
              description: 'Atmospheric dining on elevated wooden platforms overlooking the Kamogawa River lantern reflections.',
              startTime: '18:30',
              endTime: '20:30',
              durationMinutes: 120,
              cost: 6500,
              location: { name: 'Pontocho Alley', address: 'Nakagyo Ward, Kyoto', lat: 35.0068, lng: 135.7712 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Riverside', 'Culinary', 'Ambience'],
              rating: 4.7,
            },
          ],
        },
        {
          dayNumber: 5,
          date: '2026-10-14',
          title: 'Nara Sacred Deer Excursion & Transfer to Osaka',
          location: 'Nara & Osaka',
          weather: { tempC: 21, condition: 'Sunny', icon: 'Sun' },
          items: [
            {
              id: 'item-5-1',
              type: ITEM_TYPES.TRANSPORT,
              title: 'Kintetsu Express Train: Kyoto -> Nara Park',
              description: 'Quick 35-minute direct luxury sightseeing express into historic Nara basin.',
              startTime: '09:00',
              endTime: '09:40',
              durationMinutes: 40,
              cost: 1160,
              location: { name: 'Kintetsu-Nara Station', address: 'Higashimuki Nakamachi, Nara', lat: 34.6844, lng: 135.8277 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Transit', 'Rail'],
              rating: 4.6,
            },
            {
              id: 'item-5-2',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Nara Park Free-Roaming Shika Deer & Tōdai-ji Giant Buddha',
              description: 'Meet the bow-greeting sacred deer with deer crackers (shika-senbei) and marvel at the colossal bronze Daibutsu statue.',
              startTime: '10:00',
              endTime: '13:00',
              durationMinutes: 180,
              cost: 800,
              location: { name: 'Tōdai-ji', address: '406-1 Zoshicho, Nara', lat: 34.6900, lng: 135.8398 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Wildlife', 'Giant Buddha', 'UNESCO'],
              rating: 4.9,
            },
            {
              id: 'item-5-3',
              type: ITEM_TYPES.TRANSPORT,
              title: 'Rapid Train to Osaka (Namba Hub)',
              description: 'Smooth 40-minute rail hop into Osaka’s bustling southern downtown.',
              startTime: '14:30',
              endTime: '15:15',
              durationMinutes: 45,
              cost: 680,
              location: { name: 'Osaka Namba Station', address: 'Namba, Chuo Ward, Osaka', lat: 34.6669, lng: 135.5005 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Transit'],
              rating: 4.5,
            },
            {
              id: 'item-5-4',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Dotonbori Neon Canals & Glico Running Man Landmark',
              description: 'Immerse into Osaka’s electric entertainment epicenter, neon dragon signs, and river walk.',
              startTime: '18:00',
              endTime: '20:30',
              durationMinutes: 150,
              cost: 0,
              location: { name: 'Dotonbori Glico Sign', address: '1 Chome Dotonbori, Chuo Ward, Osaka', lat: 34.6687, lng: 135.5013 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Neon', 'Nightlife', 'Iconic'],
              rating: 4.8,
            },
          ],
        },
        {
          dayNumber: 6,
          date: '2026-10-15',
          title: 'Osaka Food Kingdom: Kuromon Market & Osaka Castle',
          location: 'Osaka',
          weather: { tempC: 22, condition: 'Sunny', icon: 'Sun' },
          items: [
            {
              id: 'item-6-1',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Osaka Castle & Surrounding Moat Citadel Gardens',
              description: 'Explore the 16th-century fortress of Toyotomi Hideyoshi, museum artifacts, and stone ramparts.',
              startTime: '09:30',
              endTime: '12:00',
              durationMinutes: 150,
              cost: 600,
              location: { name: 'Osaka Castle', address: '1-1 Osakajo, Chuo Ward, Osaka', lat: 34.6873, lng: 135.5262 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['History', 'Castle', 'Citadel'],
              rating: 4.7,
            },
            {
              id: 'item-6-2',
              type: ITEM_TYPES.MEAL,
              title: 'Kuromon Ichiba "The Nation’s Kitchen" Street Food Crawl',
              description: 'Taste freshly blowtorched A5 Wagyu cubes, grilled scallops in shell, Otoro sashimi, and takoyaki octopus balls.',
              startTime: '12:30',
              endTime: '14:30',
              durationMinutes: 120,
              cost: 4000,
              location: { name: 'Kuromon Market', address: '2 Chome Nihonbashi, Chuo Ward, Osaka', lat: 34.6654, lng: 135.5068 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Street Food', 'Culinary Crawl', 'Seafood'],
              rating: 4.8,
            },
            {
              id: 'item-6-3',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Shinsekai Nostalgic District & Tsutenkaku Tower',
              description: 'Retro Showa-era atmosphere with retro pinball parlors and golden Billiken statues.',
              startTime: '16:00',
              endTime: '18:00',
              durationMinutes: 120,
              cost: 900,
              location: { name: 'Tsutenkaku', address: '1 Chome-18-6 Ebisuhigashi, Naniwa Ward, Osaka', lat: 34.6525, lng: 135.5063 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Retro', 'Culture'],
              rating: 4.5,
            },
            {
              id: 'item-6-4',
              type: ITEM_TYPES.MEAL,
              title: 'Dinner: Okonomiyaki Mizuno (Michelin Bib Gourmand)',
              description: 'Watch savory Japanese cabbage pancakes griddled sizzling on hot teppan plates right in front of you.',
              startTime: '19:00',
              endTime: '20:30',
              durationMinutes: 90,
              cost: 3200,
              location: { name: 'Mizuno', address: '1 Chome-4-15 Dotonbori, Chuo Ward, Osaka', lat: 34.6682, lng: 135.5024 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Okonomiyaki', 'Bib Gourmand'],
              rating: 4.7,
            },
          ],
        },
        {
          dayNumber: 7,
          date: '2026-10-16',
          title: 'Farewell Kansai & Departure via Kansai International (KIX)',
          location: 'Osaka',
          weather: { tempC: 20, condition: 'Sunny', icon: 'Sun' },
          items: [
            {
              id: 'item-7-1',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Umeda Sky Building Floating Garden Observatory',
              description: 'Twin-tower architectural marvel connected by a floating circular sky bridge 173m above the city.',
              startTime: '09:30',
              endTime: '11:00',
              durationMinutes: 90,
              cost: 1500,
              location: { name: 'Umeda Sky Building', address: '1 Chome-1-88 Oyodonaka, Kita Ward, Osaka', lat: 34.7052, lng: 135.4904 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Architecture', 'Views'],
              rating: 4.7,
            },
            {
              id: 'item-7-2',
              type: ITEM_TYPES.ACTIVITY,
              title: 'Souvenir & Japanese Treats Shopping at Grand Front Osaka',
              description: 'Pick up authentic matcha sweets, Tokyo Banana, KitKat specialties, and handcrafted souvenirs.',
              startTime: '11:30',
              endTime: '13:00',
              durationMinutes: 90,
              cost: 5000,
              location: { name: 'Grand Front Osaka', address: '4-20 Ofukacho, Kita Ward, Osaka', lat: 34.7038, lng: 135.4950 },
              bookingStatus: BOOKING_STATUS.RECOMMENDED,
              tags: ['Shopping', 'Souvenirs'],
              rating: 4.6,
            },
            {
              id: 'item-7-3',
              type: ITEM_TYPES.TRANSPORT,
              title: 'Nankai Rapi:t Airport Express to Kansai International Airport (KIX)',
              description: 'Futuristic retro-design express train connecting Namba directly to airport terminal.',
              startTime: '14:00',
              endTime: '14:40',
              durationMinutes: 40,
              cost: 1490,
              location: { name: 'Kansai International Airport', address: 'Senshukukonaka, Tajiri, Osaka', lat: 34.4320, lng: 135.2304 },
              bookingStatus: BOOKING_STATUS.CONFIRMED,
              tags: ['Airport Transfer', 'Transit'],
              rating: 4.8,
            },
          ],
        },
      ],
    },

    lodging: [
      {
        id: 'lodge-1',
        name: 'Cerulean Tower Tokyu Hotel',
        type: 'Luxury Hotel',
        city: 'Tokyo',
        neighborhood: 'Shibuya',
        rating: 4.7,
        reviewsCount: 1420,
        pricePerNight: 28000,
        currency: 'JPY',
        nights: 2,
        checkIn: '2026-10-10',
        checkOut: '2026-10-12',
        isSelected: true,
        image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
        amenities: ['Sky View Bar', 'Fitness Center', 'High-Speed Wi-Fi', 'Concierge', 'Direct Airport Limousine Bus'],
        proximity: '5 min walk to Shibuya Crossing & Train Station',
      },
      {
        id: 'lodge-2',
        name: 'The Thousand Kyoto & Zen Garden Suites',
        type: 'Boutique Hotel & Spa',
        city: 'Kyoto',
        neighborhood: 'Shimogyo',
        rating: 4.9,
        reviewsCount: 980,
        pricePerNight: 34000,
        currency: 'JPY',
        nights: 2,
        checkIn: '2026-10-12',
        checkOut: '2026-10-14',
        isSelected: true,
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=400&fit=crop',
        amenities: ['Japanese Tea Lounge', 'Zen Meditation Courtyard', 'Luxury Onsen Style Bath', 'Michelin Restaurant'],
        proximity: '2 min walk to Kyoto Shinkansen Station',
      },
      {
        id: 'lodge-3',
        name: 'Swissôtel Nankai Osaka',
        type: 'Premier Luxury Hotel',
        city: 'Osaka',
        neighborhood: 'Namba',
        rating: 4.8,
        reviewsCount: 1850,
        pricePerNight: 30000,
        currency: 'JPY',
        nights: 2,
        checkIn: '2026-10-14',
        checkOut: '2026-10-16',
        isSelected: true,
        image: 'https://images.unsplash.com/photo-1590559899731-a382571f28d9?w=600&h=400&fit=crop',
        amenities: ['Direct Airport Train Access', 'Indoor Pool & Spa', 'Executive Lounge', 'Dotonbori Walking Distance'],
        proximity: 'Directly atop Namba Station, 8 min walk to Dotonbori',
      },
      {
        id: 'lodge-alt-1',
        name: 'Hoshinoya Kyoto (Riverside Luxury Ryokan)',
        type: 'Luxury Ryokan',
        city: 'Kyoto',
        neighborhood: 'Arashiyama',
        rating: 5.0,
        reviewsCount: 310,
        pricePerNight: 85000,
        currency: 'JPY',
        nights: 2,
        checkIn: '2026-10-12',
        checkOut: '2026-10-14',
        isSelected: false,
        image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&h=400&fit=crop',
        amenities: ['Private Wooden Riverboat Arrival', 'Seasonal Kaiseki', 'Cedarwood Open-Air Baths', 'Tea Pavilions'],
        proximity: 'Deep in Oi River Gorge, Arashiyama',
      },
    ],

    transit: [
      {
        id: 'transit-1',
        mode: 'Train',
        name: 'Narita Express (N\'EX)',
        from: 'Narita Intl Airport (NRT)',
        to: 'Shibuya Station, Tokyo',
        departureTime: '14:15',
        arrivalTime: '15:35',
        duration: '1h 20m',
        cost: 3200,
        currency: 'JPY',
        seatClass: 'Reserved Car',
        bookingReference: 'NX-94812',
        status: 'confirmed',
      },
      {
        id: 'transit-2',
        mode: 'High-Speed Rail',
        name: 'Tokaido Shinkansen Nozomi #215',
        from: 'Tokyo Station',
        to: 'Kyoto Station',
        departureTime: '09:00',
        arrivalTime: '11:15',
        duration: '2h 15m',
        cost: 14200,
        currency: 'JPY',
        seatClass: 'Green Car (Window - Mt Fuji view side)',
        bookingReference: 'SNK-77210',
        status: 'confirmed',
      },
      {
        id: 'transit-3',
        mode: 'Express Train',
        name: 'Kintetsu Sightseeing Express Aoniyoshi',
        from: 'Kyoto Station',
        to: 'Kintetsu-Nara Station',
        departureTime: '09:00',
        arrivalTime: '09:35',
        duration: '35m',
        cost: 1160,
        currency: 'JPY',
        seatClass: 'Deluxe Salon Seat',
        bookingReference: 'KT-3341',
        status: 'confirmed',
      },
      {
        id: 'transit-4',
        mode: 'Train',
        name: 'Kintetsu Nara Line Rapid Express',
        from: 'Kintetsu-Nara Station',
        to: 'Osaka Namba Station',
        departureTime: '14:30',
        arrivalTime: '15:10',
        duration: '40m',
        cost: 680,
        currency: 'JPY',
        seatClass: 'Standard Express',
        bookingReference: 'IC-NMB-88',
        status: 'confirmed',
      },
      {
        id: 'transit-5',
        mode: 'Express Train',
        name: 'Nankai Rapi:t Airport Express',
        from: 'Namba Station, Osaka',
        to: 'Kansai Airport (KIX)',
        departureTime: '14:00',
        arrivalTime: '14:38',
        duration: '38m',
        cost: 1490,
        currency: 'JPY',
        seatClass: 'Super Seat',
        bookingReference: 'NK-5520',
        status: 'confirmed',
      },
    ],

    clarifications: [],

    lastParsedIntent: {
      action: 'PLAN_TRIP',
      confidence: 0.98,
      rawPrompt: 'Initial curated Golden Route itinerary loaded.',
      timestamp: new Date().toISOString(),
      entities: {
        destination: 'Japan',
        durationDays: 7,
        travelers: { count: 2, type: 'couple' },
        budget: { amount: 450000, currency: 'JPY', tier: 'moderate' },
        interests: ['Culture', 'Culinary', 'Temples', 'Shinkansen'],
      },
      toolTrace: [
        { tool: 'planTripTool', status: 'success', summary: 'Generated balanced 7-day Tokyo-Kyoto-Osaka route' },
        { tool: 'searchLodgingTool', status: 'success', summary: 'Selected premier accommodations for 3 cities' },
        { tool: 'searchTransitTool', status: 'success', summary: 'Reserved Tokaido Shinkansen and airport express legs' },
        { tool: 'recalculateBudgetTool', status: 'success', summary: 'Calculated budget allocation with 30% safety buffer' },
      ],
    },

    auditLog: [
      {
        id: 'audit-1',
        timestamp: new Date().toISOString(),
        actionType: 'PLAN_CREATED',
        summary: 'Loaded 7-day Golden Route curated Japan plan.',
        undoable: false,
      },
    ],

    version: 1,
  };
}
